//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Hjmos.MQProxy
{

public enum ONSPullStatus {
  ONS_FOUND,
  ONS_NO_NEW_MSG,
  ONS_NO_MATCHED_MSG,
  ONS_OFFSET_ILLEGAL,
  ONS_BROKER_TIMEOUT
}

}
